# copyright: 2024 EUMETSAT
# license: LICENSE.txt
name: cmts_learn_osi_saf_wind
channels:
  - conda-forge
  - eumetsat
dependencies:
  # Core
  - conda-forge::python=3.10
  - conda-forge::jupyterlab
  - conda-forge::ipywidgets
  - conda-forge::dask
  - conda-forge::xarray=2024.1.1
  - conda-forge::netcdf4
  - conda-forge::scipy
  - conda-forge::matplotlib=3.8
  - conda-forge::cartopy
  - conda-forge::cmocean
  # External
  - eumetsat::eumdac  
  # Extension
  - conda-forge::owslib
